import java.util.ArrayList;
import java.util.List;

public class CombatState {
    public Enemy enemy;
    public float cursorPos;
    public boolean cursorForward = true;
    public float cursorSpeed = GameConfig.COMBAT_CURSOR_BASE_SPEED;
    public float cursorBaseSpeed = GameConfig.COMBAT_CURSOR_BASE_SPEED;
    public final List<CombatSegment> segments = new ArrayList<>();
    public boolean blockedThisRound;
    public int roundIndex;
    public int comboCount;
    public float comboVisual;
    public float comboPopTimer;
    public float comboResetTimer;
    public boolean inputProcessed;
    public float roundElapsed;
    public float roundDuration = GameConfig.COMBAT_ROUND_TIMEOUT;
    public boolean awaitingEnemyTurn;
    public float postInputTimer;
    public float flashTimer;
    public float shakeTimer;
    public int lastDamage;
    public SegmentType lastStrikeType;
    public String lastResult = "";
    public int lastEnemyDamage;
    public boolean lastWasTimeout;
    public float lastResolvedCursor;
    public List<Relic> relics;
    public int shards;
    public int floor = 1;
    public boolean enemyStrikeScheduled;
    public int missStreak;
    public float hitStopTimer;
    public float enemyBarFlash;
    public float playerBarFlash;
    public float intentTimer;
    public int storedGuardCharges;
    public boolean guardConsumedThisRound;
}
